### ISSUE TITLE
Does not work anymore with matrix_sdk 2.1.3

### ISSUE THREAD

**Issue by rda0** [ananace/ruby-matrix-invite-bot#1]
After the bot joins the reception room, it crashes with:

```
Traceback (most recent call last):
        12: from bin/matrix_invite_bot:83:in `<main>'
        11: from /opt/invite-bot/lib/matrix_invite_bot/bot.rb:68:in `run'
        10: from /opt/invite-bot/lib/matrix_invite_bot/bot.rb:68:in `loop'
         9: from /opt/invite-bot/lib/matrix_invite_bot/bot.rb:69:in `block in run'
         8: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:507:in `sync'
         7: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:613:in `handle_sync_response'
         6: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:613:in `each'
         5: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:618:in `block in handle_sync_response'
         4: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:618:in `each'
         3: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:620:in `block (2 levels) in handle_sync_response'
         2: from /opt/invite-bot/lib/matrix_invite_bot/extensions.rb:28:in `handle_state'
         1: from /opt/invite-bot/vendor/bundle/ruby/2.5.0/gems/matrix_sdk-2.1.3/lib/matrix_sdk/client.rb:568:in `handle_state'
/opt/invite-bot/lib/matrix_invite_bot/extensions.rb:20:in `put_state_event': undefined method `fire_state_event' for #<MatrixSdk::Room:0x000055b1091ebf80> (NoMethodError)
```

Using 2.1.2 works fine:

```
gem "matrix_sdk", "= 2.1.2"
```

Thanks a lot in the name of all our community admins!

**Comment by ananace** [comment]
Oops, had done the extension check slightly wrong, so it was overriding the new state handling design in the SDK, thanks for the report.
